### ISSUE TITLE
What if application uses modules structure or DDD?

### ISSUE THREAD

**Issue by ibrunotome** [christophrumpel/nova-notifications#7]
This configuration only will works if User maintain a structure with all models together, and all notifications together.

```php
<?php

return [

    /*
     * The namespace of your Eloquent models.
     * They will be used to check for notifiable models.
     */
    'modelNamespace' => 'App',

    /*
     * The namespace of your Laravel notifications.
     * They will be used to send out notifications.
     */
    'notificationNamespace' => 'App\Notifications',

];
```

**Comment by christophrumpel** [comment]
Hey @ibrunotome , you are right. This is the first version and I am happy to add more features when needed. Until now, It wasn't required. So how do you have your Notifications stored?

**Comment by ibrunotome** [comment]
Hey @christophrumpel, basically most of my notifications will send specially formatted for the channels:

```
 'mail',
 'broadcast',
 'database',
```

I'm using a DDD structure, so I have a models and notifications folder for each domain of the application.

**Comment by christophrumpel** [comment]
Hey @ibrunotome , I just published a news release where notifications and notifiables are loaded automatically. So the config is not necessary anymore. Can you try it out?

**Comment by ibrunotome** [comment]
Hey @christophrumpel, thanks, the Overview section works good, the Send section returns me: 

```
Call to a member function getName() on null at /vendor/christophrumpel/nova-notifications/src/Http/Controllers/NotificationClassesController.php:38)
```

**Question:** Why not use the default table notifications, that use uuid by default instead to create another table?

**Comment by christophrumpel** [comment]
hmm interesting error. Can you try a composer `dump-autoload`?

I used a separate table so that there are no conflicts if someone already uses that in some way.

**Comment by ibrunotome** [comment]
Tried, still not working, maybe cause my auth provider is edited? Don't know, cause everything works fine with the customised auth provider.

**Comment by christophrumpel** [comment]
Hmm that's interesting. Can't reproduce this error. Not sure how this provide should be part of this error. Can you show me your notification classes? Seems like the script is trying to get the name of a constructor parameter which does not exist.

**Comment by ibrunotome** [comment]
Just one is enough, right?

```php
<?php

namespace MyAppNameHere\Domain\Funds\Notifications;

use MyAppNameHere\Infrastructure\Abstracts\AbstractNotification;
use Illuminate\Notifications\Messages\BroadcastMessage;
use Illuminate\Notifications\Messages\MailMessage;

class DepositConfirmedNotification extends AbstractNotification
{
    /** @var array */
    private $data;

    /**
     * Create a new notification instance.
     *
     * @param array $data
     */
    public function __construct(array $data)
    {
        $this->data = $data;
        $this->onQueue('notifications');
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array
     */
    public function via()
    {
        return [
            'mail',
            'broadcast',
            'database',
        ];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed $notifiable
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        app()->setLocale($notifiable->locale);

        return (new MailMessage)
            ->subject(__(':app_name - A deposit was confirmed', ['app_name' => config('app.name')]))
            ->greeting(__('Hello :name', ['name' => $notifiable->profile->name]))
            ->line(__('A deposit of :symbol in the amount of :amount was confirmed.', $this->data))
            ->line(__('You can see the status of your deposits at the deposits page.'))
            ->action(__('Deposits'), url('/funds/deposits/'));
    }

    /**
     * Get the broadcastable representation of the notification.
     *
     * @param $notifiable
     *
     * @return BroadcastMessage
     */
    public function toBroadcast($notifiable)
    {
        app()->setLocale($notifiable->locale);

        return new BroadcastMessage($this->toArray($notifiable));
    }

    /**
     * Get the array representation of the notification.
     *
     * @param $notifiable
     *
     * @return array
     */
    public function toArray($notifiable)
    {
        app()->setLocale($notifiable->locale);

        $message = __('A deposit of :symbol in the amount of :amount was confirmed.', $this->data);
        $message .= (' ' . __('You can see the status of your deposits at the deposits page.'));

        return [
            'title'   => __('A deposit was confirmed'),
            'message' => $message,
            'url'     => url('/funds/deposits'),
            'color'   => 'info'
        ];
    }
}

```

Also, you can close the issue if you want, don't need to spend your time.

**Comment by ibrunotome** [comment]
In this case it's an array containing:
```
[
    'symbol' => 'BRL',
    'amount' => 200,
]
```

But this screen/modal of sending no even load for me, the red error appears first when I click on the sidebar menu for send.

**Comment by christophrumpel** [comment]
Ok, but what about your `AbstractNotification` that you use to extend the notification class instead of the default Laravel notification class. Could that be a problem?

**Comment by ibrunotome** [comment]
Here is it:

```php
<?php

namespace MyAppNameHere\Infrastructure\Abstracts;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

abstract class AbstractNotification extends Notification implements ShouldQueue
{
    use Queueable;
}

```

**Comment by christophrumpel** [comment]
anything new here?

**Comment by ibrunotome** [comment]
Holy mother, sorry. My Laravel is 5.7.10. No, stills the same, but I will close the issue, thank's for the improvement of notifiables loading automatically, this is great for who customise the Laravel structure.
